splunk:
  enabled: true
  protocol: https
  host: 192.168.100.20
  token: 4d22911c-18d9-4706-ae7b-dd1b976ca6f7
  insecureSSL: "true"
  port: "8088"
image:
  pullPolicy: "Always"
traps:
  communities:
    2c:
      - public
      - homelab
  #usernameSecrets:
  #  - sc4snmp-hlab-sha-aes
  #  - sc4snmp-hlab-sha-des

  #loadBalancerIP: The IP address in the metallb pool
  loadBalancerIP: 192.168.100.20
worker:
  # replicas: Number of replicas for worker container should two or more
  #replicaCount: 2
  # udpConnectionTimeout: timeout in seconds for SNMP operations
  #udpConnectionTimeout: 5
  logLevel: "INFO"
scheduler:
  logLevel: "INFO"
#  profiles: |
#    generic_switch:
#      frequency: 60
#      varBinds:
#        - ['SNMPv2-MIB', 'sysDescr']
#        - ['SNMPv2-MIB', 'sysName', 0]
#        - ['IF-MIB']
#        - ['TCP-MIB']
#        - ['UDP-MIB']
poller:
 # usernameSecrets:
 #   - sc4snmp-hlab-sha-aes
 #   - sc4snmp-hlab-sha-des
 # inventory: |
 #   address,port,version,community,secret,securityEngine,walk_interval,profiles,SmartProfiles,delete
 #   10.0.0.1,,3,,sc4snmp-hlab-sha-aes,,600,,,
 #   10.0.0.199,,2c,public,,,600,,,True
 #   10.0.0.100,,3,,sc4snmp-hlab-sha-des,,600,,,
sim:
  # sim must be enabled if you want to use signalFx
  enabled: false
#  signalfxToken: BCwaJ_Ands4Xh7Nrg
#  signalfxRealm: us0
mongodb:
  pdb:
    create: true
  persistence:
    storageClass: "microk8s-hostpath"
  volumePermissions:
    enabled: true
rabbitmq:
  pdb:
    create: true
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: "microk8s-hostpath"
  volumePermissions:
    enabled: true
